spring:
  application:
    name: login
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-209-61-239.compute-1.amazonaws.com:5432/d6dbma5g031sck
    username: nhdrbllxgsaxkf
    password: 0213661bb99be6e3aaa03055eed9bfcd6e511d1bdf8064605331d16a012a0233
  jpa:
    database: postgresql
    openInView: true
    show-sql: true
    hibernate:
      #ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
